### ISSUE TITLE
Data synchronization with Azure for sample data supplied with the F&E solution...

### ISSUE THREAD

**Issue by Steve-Dawkins** [microsoft/fundraising-and-engagement#10]
I can't see any notes in the Deployment Guide on how to align the Azure backend SQL database with the optional sample data installed with the Fundraising and Engagement solution?

Is there a list of entities that must be synchronized with the backend in order for the sample system to work?

**Comment by paulhasell** [comment]
We have forced a sync via the plugins by 'touching' each of the records, this has highlighted that some of the sample data have missing mandatory fields that throw error in the plugins.

To avoid sequencing issues we created T-SQL scripts to drop and re-create the FK constraints.

**Comment by Steve-Dawkins** [comment]
I used flow to force sync (see Paul's post above)using  parallel execution to touch several entities at the same time. 

This was  logged in Application Insights:
![image](https://user-images.githubusercontent.com/73112535/98236511-601e1000-1f5b-11eb-860c-7c6627cf38f4.png)

A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid…

So it looks like there's an issue with the way the API is coded to share  its database context(s).

**Comment by klbyrd** [comment]
@paulhasell and @Steve-Dawkins thank you, we are actively working on making this a less manual process. We will keep you updated. If you run into any other challenges please file a support case [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu). We are unable to handle support cases via GitHub. Thank you!
