### ISSUE TITLE
Date fields in the webresources are hardcoded to US formats

### ISSUE THREAD

**Issue by paulhasell** [microsoft/fundraising-and-engagement#11]
Date fields are hardcoded to US format (mm/dd/yy) rather than using the user locale/format in CRM

**Comment by klbyrd** [comment]
Hi @paulhasell, thank you. We are working to improve our solution for localization over this release cycle. If you have any other feedback on how we can improve in this area please let us know through this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu). I have noted your other issues above as well. Thank you!
