### ISSUE TITLE
Some of the currency fields have '$' hardcoded in the labels/description

### ISSUE THREAD

**Issue by paulhasell** [microsoft/fundraising-and-engagement#12]
![image](https://user-images.githubusercontent.com/20418710/98230612-411b8000-1f53-11eb-9478-ad1c5676682f.png)

**Comment by klbyrd** [comment]
Hi @paulhasell, thank you. We are working to improve our solution for localization over this release cycle. If you have any other feedback on how we can improve in this area please let us know through this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu). I have noted your other issues above as well. Thank you!
