### ISSUE TITLE
Hardcoded labels in webresources need to support customisation/override

### ISSUE THREAD

**Issue by paulhasell** [microsoft/fundraising-and-engagement#13]
The labels in all the web resources are hardcoded which makes it unusable for regional terms eg.

'Routing Number' in US == 'Sort Code' in UK == 'BIC' in EU
(Account Type) 'Checking' in US == 'Current' in UK/EU

**Comment by klbyrd** [comment]
Hi @paulhasell, thank you. We are working to improve our solution for localization over this release cycle. If you have any other feedback on how we can improve in this area please let us know through this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu). I have noted your other issues above as well. Thank you!
