### ISSUE TITLE
Cheque or Check?

### ISSUE THREAD

**Issue by paulhasell** [microsoft/fundraising-and-engagement#14]
The internal field names use 'Cheque' (correct spelling) while the labels all use 'Check'

`                        <div class="donationCheque hide">
                            <div class="form-group" style="display:flex;">
                                <label for="txtChequeDate" class="spnChequeDate field-label hide">Check Date</label>
                                <label for="txtChequeDate" class="spnWireDate field-label hide">Wire Date</label>
                                <input type="text" class="form-control" id="txtChequeDate" aria-label="Check/Wire Date">
                            </div>
                            <div class="form-group" style="display: flex;
">
                                <label class="spnChequeNumber field-label hide">Check Number</label>
                                <label class="spnWireNumber field-label hide">Wire Number</label>
                                <input class="form-control" type="text" id="txtChequeNumber" onkeypress="return checkIt(event);" aria-label="Check/Wire Number">
                            </div>
                        </div>
`

**Comment by klbyrd** [comment]
Hi @paulhasell, thank you. We are working to improve our solution for localization over this release cycle. If you have any other feedback on how we can improve in this area please let us know through this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu). I have noted your other issues above as well. Thank you!
