### ISSUE TITLE
Update Giving Level using aggregate query which is limited to 50K records

### ISSUE THREAD

**Issue by paulhasell** [microsoft/fundraising-and-engagement#15]
The code to calculate the completed transactions for a customer uses an aggregate query which will fail if there are more than 50K records. While this will be more than sufficient in most cases donations may be received through 3rd party sites and be marked as anonymous which will typically be assigned to a singular 'anonymous' contact. This will easily exceed the 50K limit and then throw an error on every transaction update for it.

It would be useful to have a flag on the customer to disable the rollup in this scenario.

**Comment by klbyrd** [comment]
Hi @paulhasell, thank you for your note. We will continue to improve this process over future releases. If you have further feedback or suggestions please provide it [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu). We value your feedback and want to make sure it is captured. Thank you!
