### ISSUE TITLE
Unable to build FundraisingandEngagementServices solution 

### ISSUE THREAD

**Issue by Steve-Dawkins** [microsoft/fundraising-and-engagement#2]
I get an authentication prompt when I build that I'm assuming relates to this error:

Error occurred while restoring NuGet packages: Unable to load the service index for source https://techforsocialimpact.pkgs.visualstudio.com/OneNonprofit/_packaging/OneNonprofit.Artifacts/nuget/v3/index.json.

When it compiles you end up with against 9 projects that fail to build:

NETSDK1004: Assets file 'C:\GIT\fundraising-and-engagement\CDS.Solutions.Nonprofit\FundraisingandEngagementServices\PaymentProcessors\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

Please advise on how to resolve this issue.

**Comment by savaaran** [comment]
We have updated the repository with a fix for this problem. Please refresh your local copy and try rebuilding, it should succeed now.

**Comment by Steve-Dawkins** [comment]
I can confirm that it now builds without error, thanks
