### ISSUE TITLE
Sync Records Dynamics 365 to Azure SQL 

### ISSUE THREAD

**Issue by MoeJw** [microsoft/fundraising-and-engagement#23]
I have Implemented the solution step by step following the Guideline, but When I try to import new records to crm or update records, they are not reflected on Azure sql server ... even though I tested  the url api to create some data on sql server using postman  and it works fine

**Comment by klbyrd** [comment]
Hi @MoeJw, thank you for your note. Please follow the steps below to receive support. We are unable to provide adequate support through GitHub. Please follow our support process so we can assure you receive the support you need. Thank you again for your engagement and we hope to continue to support your work with Fundraising and Engagement!
https://github.com/microsoft/fundraising-and-engagement/issues/16#issue-737067433
