### ISSUE TITLE
Migrations.sql ? missing

### ISSUE THREAD

**Issue by acehaddock** [microsoft/fundraising-and-engagement#30]
i was not able to find the Migrations.sql file in the asset files associated with this git hub 

Populate the Azure SQL Database Schema 
To populate the newly created database, open a new query window for the application database in Microsoft SQL Server Management Studio the same way as described in section ‘Create User in Application Database’ of this guide.

![image](https://user-images.githubusercontent.com/24735301/130156925-81fe17a9-1f46-436f-b26c-e6479e9ba583.png)

 

Locate the file named migrations.sql in the asset files associated with the GitHub release you are deploying. Paste the contents of the file to the query window and press Execute.

 
![image](https://user-images.githubusercontent.com/24735301/130156927-432c450a-deaf-49fe-a50d-5aec6dd127b3.png)

Successful result should look like this:
![image](https://user-images.githubusercontent.com/24735301/130156932-acad72bd-9089-4817-a826-a44758ceb49a.png)

**Comment by savaaran** [comment]
Hi, you can find the latest migrations file from the Releases. Please take the ef-migrations.sql file from the v1.2.3.1 release. You can find this file by clicking on 'Tags' on the Code page, navigating to v1.2.3.1 release and expanding the Assets.
