### ISSUE TITLE
Getting 400 Bad Request from DataPush

### ISSUE THREAD

**Issue by paulhasell** [microsoft/fundraising-and-engagement#32]
Hi, the 3rd party Web API client is throwing a 400: Bad Request error pushing pack to Dataverse. It's comming out of the ServerToServerAuthentication component. This is a black box and I have no way to debug it properly

**Comment by klbyrd** [comment]
Hi @paulhasell, please file a support case through Power Platform Admin Center (https://admin.powerplatform.microsoft.com/) so we can assist. Thank you!
