### ISSUE TITLE
Sample data does not create contacts or accounts

### ISSUE THREAD

**Issue by lisacrosbie** [microsoft/fundraising-and-engagement#35]
Most recent sample data file does not create any contacts or organizations in the sample data. All other entities are created but with blank values in the contact and account lookups. 

![1 transactions](https://user-images.githubusercontent.com/94160948/141420297-89a24208-8212-4841-bfd5-3158dfb69acc.jpg)
![2 opportunities](https://user-images.githubusercontent.com/94160948/141420311-0e9c6a93-e098-4298-b139-6d491a195cc8.jpg)
![3 blank contacts](https://user-images.githubusercontent.com/94160948/141420322-67db0ca1-74a1-4eef-9db8-2a839984dd29.jpg)
[ImportDataDetailLog.log](https://github.com/microsoft/fundraising-and-engagement/files/7525308/ImportDataDetailLog.log)

**Comment by vuhrova** [comment]
We updated the sample data set and the issue with not-creating contacts should be resolved now.
