### ISSUE TITLE
Question regarding architecture

### ISSUE THREAD

**Issue by liloia** [microsoft/fundraising-and-engagement#5]
Why is a separate (redundant) database needed apart from being able to process transactions when D365 is not available?

**Comment by klbyrd** [comment]
Hi @liloia thank you for your question. Can you please submit a support case [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu)? Our team will be able to better help you through the support process. Thank you!

**Comment by liloia** [comment]
@klbyrd sure, thanks!
