### ISSUE TITLE
401 error from all API calls having followed Deployment Guide...

### ISSUE THREAD

**Issue by Steve-Dawkins** [microsoft/fundraising-and-engagement#6]
The Deployment Guide has steps to create a .Net Framework based Console application used to generate an encrypted passcode. 

The 401 error is a result of the encoding used by the console app's use of  System.Text.Encoding.Default.GetString() that does not default in  .Net Framework to UTF8.  

Workaround, alter the encoding statement to specify UTF8 or build the console app using .Net Core

**Comment by klbyrd** [comment]
Hi @Steve-Dawkins, thank you for questions and feedback. Can you please submit a case [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9O0k5_UUiBCoZBVVnq-IHZUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WC4u)? Our team can better assist you through the support process. Thank you!

**Comment by Steve-Dawkins** [comment]
Hi Collaborator, I don't need support, just thought you'd like to know of the issue and it's workaround. Please feel free to pass it through  your support process.

**Comment by klbyrd** [comment]
Hi, thank you! We will pass it on and update any documentation where needed.

**Comment by LaurieHeer** [comment]
@Steve-Dawkins I think I may be having a similar issue. Can you please tell me exactly what to change line 333 to? I understand the concept of what you are saying the problem is, but I don't know how to fix it. 

Thank you in advance,
Laurie

`{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplate",
        "message": "Unable to process template language expressions for resource '/subscriptions/b6f78187-bec9-4f36-91f4-b37e6996bfe6/resourceGroups/FundraisingandEngagement/providers/Microsoft.Web/sites/Sierra-ApiApp-prod' at line '333' and column '9'. 'The template language function 'base64ToString' was invoked with a parameter that is not valid. The value cannot be decoded from base64 representation.'",
        "additionalInfo": [
            {
                "type": "TemplateViolation",
                "info": {
                    "lineNumber": 333,
                    "linePosition": 9,
                    "path": ""
                }
            }
        ]
    }
}`

**Comment by V-Rohit** [comment]
Hi @LaurieHeer, As per my understanding, you are getting the error while generating the padlock token(Passcode), above error detail is not enough to understand the problem. I would really appreciate if you submit a case using below URL path and attach the screenshot of the error and complete error log.
https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu?
