### ISSUE TITLE
SQL Login/User creation needs to be clearer in Deployment Guide....

### ISSUE THREAD

**Issue by Steve-Dawkins** [microsoft/fundraising-and-engagement#7]
Page 24 is easily misunderstood:

![image](https://user-images.githubusercontent.com/73112535/97976938-4f3a9680-1dc3-11eb-8ac3-216845bc5c8b.png)

It would be easier to understand if the steps said:

_Run this against the master database:

CREATE LOGIN SQL_Login_Name (e.g. Contoso_prod_user)
WITH PASSWORD = 'Password as entered during ARM Template configuration'
GO
CREATE USER SQL_Login_Name e.g. Contoso_prod_user
FOR LOGIN SQL_Login_Name e.g. Contoso_prod_user
WITH DEFAULT_SCHEMA=dbo
GO

Run this against the provisioned SQL Database:

CREATE USER SQL_Login_Name e.g. Contoso_prod_user
FOR LOGIN SQL_Login_Name e.g. Contoso_prod_user
WITH DEFAULT_SCHEMA=dbo
GO

EXEC sp_addrolemember N'db_owner', N'SQL_Login_Name e.g. Contoso_prod_user'
GO_

Without the User in the master database API calls fail and you have to look in at AI traces/exceptions to determine the cause of the failure.

**Comment by vuhrova** [comment]
Hi @Steve-Dawkins, the deployment guide was updated, thank you for your review!
