### ISSUE TITLE
What is step C in 3.	Background Services Web Job URL - Deployment Guide

### ISSUE THREAD

**Issue by Steve-Dawkins** [microsoft/fundraising-and-engagement#8]
Page 40 Deployment Guide

![image](https://user-images.githubusercontent.com/73112535/97977358-01725e00-1dc4-11eb-9a31-58be7f937b32.png)

What's meant by _C. Locate and view the function ‘DataPushHttp'_  as it has nothing to do with step D ?

**Comment by vuhrova** [comment]
Hi @Steve-Dawkins this step was removed, thank you for your response.
