### ISSUE TITLE
Source code in download has changed since 12th October - code for plugins no longer present?

### ISSUE THREAD

**Issue by Steve-Dawkins** [microsoft/fundraising-and-engagement#9]
Only the folder named  FundraisingandEngagementServices is present in the current download.

On 12/10/2010 we saw two additional folders that contained the code for the F&E plugins:

FundraisingandEngagementResources
FundraisingandEngagement

Is the code for the plugins still available and if so where?

**Comment by klbyrd** [comment]
Hi @Steve-Dawkins, the code is available for the plugins and the other Dynamics components via [AppSource](https://appsource.microsoft.com/en-us/product/dynamics-365/msnfp.msftnonprofitfundraisingandengagement) as a managed package. The repo just has the Azure components available.

**Comment by paulhasell** [comment]
I downloaded the ZIP package on day 1 (12 October 2020) and it has the source of the Plugins and Web Resources as well as the exported customisations so this used to be available:

![image](https://user-images.githubusercontent.com/20418710/98223169-a4a0b000-1f49-11eb-83a5-44d0b69ecefc.png)
![image](https://user-images.githubusercontent.com/20418710/98223236-c0a45180-1f49-11eb-8027-0df0e1bb025b.png)
![image](https://user-images.githubusercontent.com/20418710/98223315-d44fb800-1f49-11eb-9139-b274c7caa576.png)

**Comment by klbyrd** [comment]
Hi @paulhasell, yes we had them available on GitHub for a short time until they were available on AppSource. Now that they are available on AppSource we are directing all customers there to ensure we can provide the best deployment experience and deliver upgrades seamlessly. Thank you!

**Comment by paulhasell** [comment]
But AppSource won't include the actual source code will it? Isn't it just the installable CDS solution?

**Comment by Benema3000** [comment]
We can't install the managed package through the Solution Center (Switzerland is not a supported Region). Is there any way for us to access the source code?

**Comment by klbyrd** [comment]
Hi @Benema3000, Solution Center does support Switzerland. If you are running into issues, please file a support ticket through PPAC. That team can help you. Thank you!

**Comment by Benema3000** [comment]
@klbyrd thanks for the response. Sorry to use this channel again, but it's not easy to find a partner that helps us to open a ticket (we are a small NGO): you are saying, that the fundraising and engagement solution can be installed on a swiss environment? Because we don't seem to be able to do that. Our environment (with Dynamics installed) does not appear when trying to deploy the fundraising and engagement solution.
